name          'puppet-skyline'
version       '0.1.0'
source        'https://github.com/tombooth/puppet-skyline.git'
author        'Tom Booth'
license       'MIT'
summary       'Puppet module to install Skyline'
description   'Puppet module to install Skyline'
project_page  'https://github.com/tombooth/puppet-skyline'

dependency 'puppetlabs/stdlib',    '>= 4.1.0'
dependency 'footballradar/python', '>= 0.1.0'
dependency 'puppetlabs/vcsrepo',   '>= 0.2.0'
